apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: ouctl
spec:
  version: "v_VERSION_"
  homepage: https://github.com/tremolosecurity/openunison-control
  shortDescription: "Deploy OpenUnison for authentication and automation"
  description: Deploys OpenUnison, see https://openunison.github.io/deployauth/ for details
  platforms:
  - selector:
      matchExpressions:
      - key: "os"
        operator: "In"
        values:
        - darwin
    uri: https://nexus.tremolo.io/repository/_REPO_/ouctl-_VERSION_-macos.zip
    sha256: _MAC_SHA_
    files:
    - from: "ouctl"
      to: "ouctl"
    - from: "LICENSE"
      to: "LICENSE"
    bin: ouctl
  - selector:
      matchExpressions:
      - key: "os"
        operator: "In"
        values:
        - linux
    uri: https://nexus.tremolo.io/repository/_REPO_/ouctl-_VERSION_-linux.zip
    sha256: _LINUX_SHA_
    files:
    - from: "ouctl"
      to: "ouctl"
    - from: "LICENSE"
      to: "LICENSE"
    bin: ouctl
  - selector:
      matchExpressions:
      - key: "os"
        operator: "In"
        values:
        - windows
    uri: https://nexus.tremolo.io/repository/_REPO_/ouctl-_VERSION_-win.zip
    sha256: _WIN_SHA_
    files:
    - from: "ouctl.exe"
      to: "ouctl.exe"
    - from: "LICENSE"
      to: "LICENSE"
    bin: ouctl.exe