openapi: 3.0.1
info:
  title: OpenUnison CRD
  description: OpenUnison ScaleJS Register API
  version: v6
servers:
- url: /
paths: {}
components:
  schemas:
    OpenUnison:
      type: object
      properties:
        spec:
          $ref: '#/components/schemas/OpenUnison_spec'
        status:
          $ref: '#/components/schemas/OpenUnison_status'
    OpenUnison_spec_openshift_git:
      type: object
      properties:
        repo:
          type: string
        branch:
          type: string
        dir:
          type: string
    OpenUnison_spec_openshift:
      type: object
      properties:
        git:
          $ref: '#/components/schemas/OpenUnison_spec_openshift_git'
        builder_image:
          type: string
    OpenUnison_spec_names:
      type: object
      properties:
        name:
          type: string
        service_name:
          type: string
        env_var:
          type: string
    OpenUnison_spec_annotations:
      type: object
      properties:
        name:
          type: string
        value:
          type: string
    OpenUnison_spec_hosts:
      type: object
      properties:
        names:
          type: array
          items:
            $ref: '#/components/schemas/OpenUnison_spec_names'
        ingress_name:
          type: string
        ingress_type:
          type: string
        secret_name:
          type: string
        annotations:
          type: array
          items:
            $ref: '#/components/schemas/OpenUnison_spec_annotations'
    OpenUnison_spec_deployment_data_tokenrequest_api:
      type: object
      properties:
        enabled:
          type: boolean
        audience:
          type: string
        expirationSeconds:
          type: integer
    OpenUnison_spec_deployment_data_resources_requests:
      type: object
      properties:
        memory:
          type: string
        cpu:
          type: string
    OpenUnison_spec_deployment_data_resources:
      type: object
      properties:
        requests:
          $ref: '#/components/schemas/OpenUnison_spec_deployment_data_resources_requests'
        limits:
          $ref: '#/components/schemas/OpenUnison_spec_deployment_data_resources_requests'
    OpenUnison_spec_deployment_data:
      type: object
      properties:
        tokenrequest_api:
          $ref: '#/components/schemas/OpenUnison_spec_deployment_data_tokenrequest_api'
        readiness_probe_command:
          type: array
          items:
            type: string
        liveness_probe_command:
          type: array
          items:
            type: string
        node_selectors:
          type: array
          items:
            $ref: '#/components/schemas/OpenUnison_spec_annotations'
        pull_secret:
          type: string
        resources:
          $ref: '#/components/schemas/OpenUnison_spec_deployment_data_resources'
    OpenUnison_spec_openunison_network_configuration_error_pages:
      type: object
      properties:
        code:
          type: integer
        location:
          type: string
    OpenUnison_spec_openunison_network_configuration_queue_configuration_params:
      type: object
      properties:
        name:
          type: string
        source_type:
          type: string
          enum:
          - static
          - environment
        value:
          type: string
    OpenUnison_spec_openunison_network_configuration_queue_configuration:
      type: object
      properties:
        use_internal_queue:
          type: boolean
        max_producers:
          type: integer
        connection_factory:
          type: string
        max_consumers:
          type: integer
        max_sessions_per_connection:
          type: integer
        task_queue_name:
          type: string
        smtp_queue_name:
          type: string
        encryption_key_name:
          type: string
        num_queues:
          type: integer
        multi_task_queues:
          type: boolean
        keep_alive_millis:
          type: integer
        params:
          type: array
          items:
            $ref: '#/components/schemas/OpenUnison_spec_openunison_network_configuration_queue_configuration_params'
    OpenUnison_spec_openunison_network_configuration:
      type: object
      properties:
        force_to_lower_case:
          type: boolean
        open_port:
          type: integer
        open_external_port:
          type: integer
        secure_port:
          type: integer
        secure_external_port:
          type: integer
        ldap_port:
          type: integer
        ldaps_port:
          type: integer
        ldaps_key_name:
          type: string
        force_to_secure:
          type: boolean
        activemq_dir:
          type: string
        client_auth:
          type: string
        allowed_client_names:
          type: array
          items:
            type: string
        ciphers:
          type: array
          items:
            type: string
        path_to_deployment:
          type: string
        path_to_env_file:
          type: string
        secure_key_alias:
          type: string
        allowed_tls_protocols:
          type: array
          items:
            type: string
        quartz_dir:
          type: string
        context_root:
          type: string
        disable_http2:
          type: boolean
        allow_un_escaped_chars:
          type: string
        welecome_pages:
          type: array
          items:
            type: string
        error_pages:
          type: array
          items:
            $ref: '#/components/schemas/OpenUnison_spec_openunison_network_configuration_error_pages'
        redirect_to_context_root:
          type: boolean
        queue_configuration:
          $ref: '#/components/schemas/OpenUnison_spec_openunison_network_configuration_queue_configuration'
    OpenUnison_spec_source:
      type: object
      properties:
        url:
          type: string
        xml:
          type: string
    OpenUnison_spec_mapping:
      type: object
      properties:
        entity_id:
          type: string
        post_url:
          type: string
        redirect_url:
          type: string
        logout_url:
          type: string
        signing_cert_alias:
          type: string
        encryption_cert_alias:
          type: string
    OpenUnison_spec_saml_remote_idp:
      type: object
      properties:
        source:
          $ref: '#/components/schemas/OpenUnison_spec_source'
        mapping:
          $ref: '#/components/schemas/OpenUnison_spec_mapping'
    OpenUnison_spec_key_store_update_controller:
      type: object
      properties:
        image:
          type: string
        schedule:
          type: string
        days_to_expire:
          type: integer
    OpenUnison_spec_key_store_static_keys:
      type: object
      properties:
        name:
          type: string
        version:
          type: integer
    OpenUnison_spec_key_store_trusted_certificates:
      type: object
      properties:
        name:
          type: string
        pem_data:
          type: string
    OpenUnison_spec_key_store_key_pairs_create_data_patch_info:
      type: object
      properties:
        url:
          type: string
        annotation_name:
          type: string
    OpenUnison_spec_key_store_key_pairs_create_data_secret_info:
      type: object
      properties:
        type_of_secret:
          type: string
        cert_name:
          type: string
        key_name:
          type: string
    OpenUnison_spec_key_store_key_pairs_create_data:
      type: object
      properties:
        target_namespace:
          type: string
        sign_by_k8s_ca:
          type: boolean
        server_name:
          type: string
        subject_alternative_names:
          type: array
          items:
            type: string
        key_size:
          type: integer
        ca_cert:
          type: boolean
        delete_pods_labels:
          type: array
          items:
            type: string
        patch_info:
          $ref: '#/components/schemas/OpenUnison_spec_key_store_key_pairs_create_data_patch_info'
        secret_info:
          $ref: '#/components/schemas/OpenUnison_spec_key_store_key_pairs_create_data_secret_info'
    OpenUnison_spec_key_store_key_pairs_keys:
      type: object
      properties:
        name:
          type: string
        tls_secret_name:
          type: string
        import_into_ks:
          type: string
          enum:
          - keypair
          - certificate
          - none
        replace_if_exists:
          type: boolean
        create_data:
          $ref: '#/components/schemas/OpenUnison_spec_key_store_key_pairs_create_data'
    OpenUnison_spec_key_store_key_pairs:
      type: object
      properties:
        create_keypair_template:
          type: array
          items:
            $ref: '#/components/schemas/OpenUnison_spec_annotations'
        keys:
          type: array
          items:
            $ref: '#/components/schemas/OpenUnison_spec_key_store_key_pairs_keys'
    OpenUnison_spec_key_store:
      type: object
      properties:
        update_controller:
          $ref: '#/components/schemas/OpenUnison_spec_key_store_update_controller'
        static_keys:
          type: array
          items:
            $ref: '#/components/schemas/OpenUnison_spec_key_store_static_keys'
        trusted_certificates:
          type: array
          items:
            $ref: '#/components/schemas/OpenUnison_spec_key_store_trusted_certificates'
        key_pairs:
          $ref: '#/components/schemas/OpenUnison_spec_key_store_key_pairs'
    OpenUnison_spec:
      type: object
      properties:
        image:
          type: string
        replicas:
          type: integer
        enable_activemq:
          type: boolean
        activemq_image:
          type: string
        dest_secret:
          type: string
        source_secret:
          type: string
        secret_data:
          type: array
          items:
            type: string
        myvd_configmap:
          type: string
        openshift:
          $ref: '#/components/schemas/OpenUnison_spec_openshift'
        hosts:
          type: array
          items:
            $ref: '#/components/schemas/OpenUnison_spec_hosts'
        deployment_data:
          $ref: '#/components/schemas/OpenUnison_spec_deployment_data'
        non_secret_data:
          type: array
          items:
            $ref: '#/components/schemas/OpenUnison_spec_annotations'
        openunison_network_configuration:
          $ref: '#/components/schemas/OpenUnison_spec_openunison_network_configuration'
        saml_remote_idp:
          type: array
          items:
            $ref: '#/components/schemas/OpenUnison_spec_saml_remote_idp'
        run_sql:
          type: string
        sql_check_query:
          type: string
        key_store:
          $ref: '#/components/schemas/OpenUnison_spec_key_store'
    OpenUnison_status_conditions:
      type: object
      properties:
        lastTransitionTime:
          type: string
        status:
          type: string
        type:
          type: string
    OpenUnison_status:
      type: object
      properties:
        conditions:
          $ref: '#/components/schemas/OpenUnison_status_conditions'
        digest:
          type: string
        idpCertificateFingerprints:
          type: object
          additionalProperties: true
x-original-swagger-version: "2.0"
